# Copyright (C) 2011 by Danny de Jong
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.




##### General #####

# The default title is used when a player doesn't have any title set.
default_title: ''
# Set the following to true if you want to players to not be able to use any other title than the default title:
force_default: false

##### Messages #####

# When you try to use a player-only command on the console:
message_command_player_only: Command is for player use only.
# When a problem occurred on the server while processing your command:
message_internal_error: An internal error occurred.
# When the name of a title that you are trying to register is invalid: (name)
message_invalid_title_name: '"$name$" is invalid.'
# When you try to execute a command but don't have the permissions for it:
message_no_permissions: You don't have the required permissions to do that.
# When you don't own the title you want to use: (title_name)
message_no_title: You don't own title "$title_name$".
# When you don't own any titles:
message_no_titles: You don't own any titles (yet).
# When a player already owns a certain title: (player_name, title_name)
message_player_owns_title: Player "$player_name$" already owns title "$title_name$".
# When a player doesn't exist: (player_name)
message_player_not_exists: Player "$player_name$" doens't exist.
# When a player doesn't own a title:
message_player_not_owns_title: Player "$player_name$" doesn't own title "$title_name$".
# When you try to register a title with a name that exists already: (title_name)
message_title_exists: A title with the same name is registered already.
# When you give a title to someone: (title_name, player_name)
message_title_given: Title "$title_name$" has been given to "$player_name$".
# When you try to unregister a title with a name that doesn't exist: (title_name)
message_title_not_exists: There is no title registered with that name.
# When you have registered a title: (title_name)
message_title_registered: Title "$title_name$" has been registered.
# When you take a title away from someone: (title_name, player_name)
message_title_taken: Title "$title_name$" has been taken from "$player_name$".
# When you have unregistered a title: (title_name)
message_title_unregistered: Title "$title_name$" has been unregistered.
# When a players starts using a title: (display_name, title_name)
message_title_use: You are now called "$display_name$".


##### MySQL #####

sql_host: localhost
sql_port: 3306
sql_username: root
sql_password: pass
sql_database: my_titles